spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store-services
    username: root
    password: mysql!@#123
  application:
    name: STORE-SERVICES
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true